openapi: 3.0.0
info:
  title: Vehicle Details API
  version: 1.0.0
  description: API for managing vehicle details
servers:
  - url: http://localhost:3000/v1

paths:
  /vehicles:
    get:
      summary: Get all vehicles
      description: Retrieves a list of all vehicles with their details
      parameters:
        - name: page
          in: query
          required: false
          description: Page number for pagination
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          required: false
          description: Number of items per page
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: List of vehicles retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: './schemas/vehicle.yaml#/components/schemas/VehicleDetails'
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      limit:
                        type: integer
                      pages:
                        type: integer
        '400':
          $ref: './common/responses.yaml#/responses/BadRequest'
        '401':
          $ref: './common/responses.yaml#/responses/Unauthorized'

  /vehicles/{vehicleId}:
    get:
      summary: Get vehicle details
      description: Retrieves details of a specific vehicle
      parameters:
        - name: vehicleId
          in: path
          required: true
          description: The ID of the vehicle
          schema:
            type: string
            format: uuid
            example: "1e03a16e-8275-4285-92e4-c80c87085399"
      responses:
        '200':
          description: Vehicle details retrieved successfully
          content:
            application/json:
              schema:
                $ref: './schemas/vehicle.yaml#/components/schemas/VehicleDetails'
        '400':
          $ref: './common/responses.yaml#/responses/BadRequest'
        '401':
          $ref: './common/responses.yaml#/responses/Unauthorized'
        '404':
          $ref: './common/responses.yaml#/responses/NotFound' 