services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /app/index.yaml
    volumes:
      - ./index.yaml:/app/index.yaml:ro
      - ./v1:/app/v1:ro
      - ./v2:/app/v2:ro
    restart: unless-stopped 