openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
  description: Complete API documentation with external references

servers:
  - url: https://api.optipix.eu/v1
  - url: https://api.optipix.eu/v2

paths:
  # Auth paths
  /login:
    $ref: './v1/auth.yaml#/paths/~1login'
  /users/{userId}/login:
    $ref: './v1/auth.yaml#/paths/~1users~1{userId}~1login'

  # Client paths
  /customers/{customerId}/clients:
    $ref: './v1/client.yaml#/paths/~1customers~1{customerId}~1clients'
  /clients/{clientId}:
    $ref: './v1/client.yaml#/paths/~1clients~1{clientId}'
  /clients/{clientId}/change-customer:
    $ref: './v1/client.yaml#/paths/~1clients~1{clientId}~1change-customer'

  # User paths
  /clients/{clientId}/users:
    $ref: './v1/user.yaml#/paths/~1clients~1{clientId}~1users'
  /users/{userId}:
    $ref: './v1/user.yaml#/paths/~1users~1{userId}'
  /users/{userId}/change-password:
    $ref: './v1/user.yaml#/paths/~1users~1{userId}~1change-password'
  /password/forgot:
    $ref: './v1/user.yaml#/paths/~1password~1forgot'
  /password/reset:
    $ref: './v1/user.yaml#/paths/~1password~1reset'

  # Vehicle paths
  /users/{userId}/vehicles:
    $ref: './v1/vehicle.yaml#/paths/~1users~1{userId}~1vehicles'
  /users/{userId}/vehicles/{vehicleId}:
    $ref: './v1/vehicle.yaml#/paths/~1users~1{userId}~1vehicles~1{vehicleId}'

  # Vehicle Details paths
  /vehicles:
    $ref: './v1/vehicleDetails.yaml#/paths/~1vehicles'
  /vehicles/{vehicleId}:
    $ref: './v1/vehicleDetails.yaml#/paths/~1vehicles~1{vehicleId}'

  # Vehicle Body Type paths
  /vehicleBodyTypes:
    $ref: './v1/vehicleBodyType.yaml#/paths/~1vehicleBodyTypes'
  /vehicleBodyTypes/{vehicleBodyTypeId}:
    $ref: './v1/vehicleBodyType.yaml#/paths/~1vehicleBodyTypes~1{vehicleBodyTypeId}'

  # Image paths
  /images:
    $ref: './v1/image.yaml#/paths/~1images'
  /images/{imageId}:
    $ref: './v1/image.yaml#/paths/~1images~1{imageId}'
  /images/upload:
    $ref: './v1/image.yaml#/paths/~1images~1upload'
  /images/{imageId}/process:
    $ref: './v1/image.yaml#/paths/~1images~1{imageId}~1process'

  # Customer Settings paths
  /customers/{customerId}/settings:
    $ref: './v1/customerSettings.yaml#/paths/~1customers~1{customerId}~1settings'

  # V2 Customer paths
  /v2/customers:
    $ref: './v2/customer.yaml#/paths/~1customers'
  /v2/customers/{customerId}:
    $ref: './v2/customer.yaml#/paths/~1customers~1{customerId}'

components:
  schemas:
    # Auth schemas
    LoginRequest:
      $ref: './v1/schemas/auth.yaml#/components/schemas/LoginRequest'
    LoginResponse:
      $ref: './v1/schemas/auth.yaml#/components/schemas/LoginResponse'
    # Required schemas for auth
    User:
      $ref: './v1/schemas/user.yaml#/components/schemas/User'
    UserRole:
      $ref: './v1/schemas/user.yaml#/components/schemas/UserRole'
    UserFile:
      $ref: './v1/schemas/user.yaml#/components/schemas/UserFile'

    # Client schemas
    Client:
      $ref: './v1/schemas/client.yaml#/components/schemas/Client'
    ClientSettings:
      $ref: './v1/schemas/client.yaml#/components/schemas/ClientSettings'

    # Customer Settings schemas
    CustomerSettings:
      $ref: './v1/schemas/customerSettings.yaml#/components/schemas/CustomerSettings'

    # V2 Customer schemas
    CustomerV2:
      $ref: './v2/schemas/customer.yaml#/components/schemas/Customer'

    # Vehicle schemas
    Vehicle:
      $ref: './v1/schemas/vehicle.yaml#/components/schemas/Vehicle'
    VehicleDetails:
      $ref: './v1/schemas/vehicle.yaml#/components/schemas/VehicleDetails'
    VehicleBodyType:
      $ref: './v1/schemas/vehicle.yaml#/components/schemas/VehicleBodyType'

    # Image schemas
    Image:
      $ref: './v1/schemas/image.yaml#/components/schemas/Image'
    ProcessImageRequest:
      $ref: './v1/schemas/image.yaml#/components/schemas/ProcessImageRequest'

  responses:
    BadRequest:
      $ref: './v1/common/responses.yaml#/responses/BadRequest'
    NotFound:
      $ref: './v1/common/responses.yaml#/responses/NotFound'
    Unauthorized:
      $ref: './v1/common/responses.yaml#/responses/Unauthorized'
    Forbidden:
      $ref: './v1/common/responses.yaml#/responses/Forbidden'

  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key

security:
  - ApiKey: []